# Generated by Django 5.0.8 on 2025-09-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup_doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledocx',
            name='estatus',
            field=models.IntegerField(blank=True, choices=[(1, 'Processing'), (2, 'Processed')], default=1, verbose_name='Process estatus'),
        ),
        migrations.AlterField(
            model_name='articledocxmarkup',
            name='estatus',
            field=models.IntegerField(blank=True, choices=[(1, 'Processing'), (2, 'Processed')], default=1, verbose_name='Process estatus'),
        ),
    ]
