# Generated by Django 6.0.5 on 2026-06-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markup_doc', '0003_remove_articledocxmarkup_dateiso_and_more'),
        ('markup_doc', '0004_articledocxmarkup_xref_status'),
    ]

    operations = [
    ]
