from django.utils.translation import gettext_lazy as _

ERROR = "ERROR"
EXCEPTION = "EXCEPTION"
INFO = "INFO"
WARNING = "WARNING"

EVENT_MSG_TYPE = [
    (ERROR, _("error")),
    (WARNING, _("warning")),
    (INFO, _("info")),
    (EXCEPTION, _("exception")),
]


PROGRESS_STATUS_IGNORED = "IGNORED"
PROGRESS_STATUS_REPROC = "REPROC"
PROGRESS_STATUS_TODO = "TODO"
PROGRESS_STATUS_DOING = "DOING"
PROGRESS_STATUS_DONE = "DONE"
PROGRESS_STATUS_PENDING = "PENDING"

PROGRESS_STATUS = (
    (PROGRESS_STATUS_REPROC, _("To reprocess")),
    (PROGRESS_STATUS_TODO, _("To do")),
    (PROGRESS_STATUS_DONE, _("Done")),
    (PROGRESS_STATUS_DOING, _("Doing")),
    (PROGRESS_STATUS_PENDING, _("Pending")),
    (PROGRESS_STATUS_IGNORED, _("ignored")),
)

XML_DOCUMENT_PARSING_ERROR = "XPE"
XML_DOCUMENT_VALIDATION_ERROR = "VDE"
XML_DOCUMENT_CONVERSION_TO_DOCX_ERROR = "CDE"
XML_DOCUMENT_CONVERSION_TO_HTML_ERROR = "CHE"
XML_DOCUMENT_CONVERSION_TO_PDF_ERROR = "CPE"
XML_DOCUMENT_CONVERSION_TO_TEX_ERROR = "CTE"
XML_DOCUMENT_CONVERSION_TO_PUBMED_ERROR = "PME"
XML_DOCUMENT_CONVERSION_TO_PMC_ERROR = "PCE"
XML_DOCUMENT_UNKNOWN_ERROR = "UNE"

XML_DOCUMENT_EVENT = [
    (XML_DOCUMENT_PARSING_ERROR, _("XML Parsing Error")),
    (XML_DOCUMENT_VALIDATION_ERROR, _("XML Validation Error")),
    (XML_DOCUMENT_CONVERSION_TO_DOCX_ERROR, _("XML Conversion to DOCX Error")),
    (XML_DOCUMENT_CONVERSION_TO_HTML_ERROR, _("XML Conversion to HTML Error")),
    (XML_DOCUMENT_CONVERSION_TO_PDF_ERROR, _("XML Conversion to PDF Error")),
    (XML_DOCUMENT_CONVERSION_TO_TEX_ERROR, _("XML Conversion to TEX Error")),
    (XML_DOCUMENT_CONVERSION_TO_PUBMED_ERROR, _("XML Conversion to PubMed Error")),
    (XML_DOCUMENT_CONVERSION_TO_PMC_ERROR, _("XML Conversion to PMC Error")),
    (XML_DOCUMENT_UNKNOWN_ERROR, _("Unknown Error")),
]
