# Generated by Django 5.0.8 on 2025-10-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamamodel',
            name='download_status',
            field=models.IntegerField(blank=True, choices=[(1, 'No model'), (2, 'Downloading model'), (3, 'Model downloaded'), (4, 'Download error')], default=1, verbose_name='Local model status'),
        ),
    ]
