# Generated by Django 6.0.5 on 2026-06-11 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_manager', '0004_spspackagevalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLDocumentPMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmc_file', models.FileField(upload_to='xml_manager/pmc/', verbose_name='PMC XML File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('xml_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmcs', to='xml_manager.xmldocument', verbose_name='XML Document')),
            ],
            options={
                'verbose_name': 'XML Document PMC',
                'verbose_name_plural': 'XML Document PMCs',
            },
        ),
        migrations.CreateModel(
            name='XMLDocumentPubMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_file', models.FileField(upload_to='xml_manager/pubmed/', verbose_name='PubMed XML File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('xml_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubmeds', to='xml_manager.xmldocument', verbose_name='XML Document')),
            ],
            options={
                'verbose_name': 'XML Document PubMed',
                'verbose_name_plural': 'XML Document PubMeds',
            },
        ),
    ]
