# Generated by Django 5.0.8 on 2025-10-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_xmldocumentevent_error_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalevent',
            options={'ordering': ['-created'], 'verbose_name': 'General Event', 'verbose_name_plural': 'General Events'},
        ),
    ]
